"use client";

import { useState } from "react";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Search, Plus, Play, Settings2, Clock, Loader2, ArrowUpRight, Sparkles, ChevronLeft } from "lucide-react";
import { jobAgentRequest as request, type Candidate, type Overview } from "@/lib/job-agent";

type Mode = "required" | "preferred";
type Config = {
  name: string; target_roles: string; preferred_industries: string; industry_mode: Mode;
  location_preferences: string; location_mode: Mode; employment_type: "any" | "contract" | "non_contract";
  employment_mode: Mode; exclusions: string; additional_preferences: string; prefer_overseas_employers: boolean;
  posted_within_days: number; source_ids: string[]; employer_urls: string[]; max_candidates: number; max_sources: number;
  schedule_enabled: boolean; timezone: string; local_time: string;
};
type Saved = { id: string; revision: number; config: Config };
type Run = { id: string; name: string; search_id?: string; status: string; phase: string; trigger: string;
  started_at: string; completed_at?: string; new_jobs: number; verified: number; duplicates: number; errors: number;
  counts: Record<string, number> };
type Result = { candidate: { firm_name?: string; title?: string; source_url?: string }; candidate_id?: string;
  outcome: string; reason: string; already_known?: boolean; contract_status?: string;
  contacts?: { verified: number }; decision?: { location?: string; posted_date?: string; work_arrangement?: string;
    search_checks?: { criterion: string; result: string; reason: string; confidence: number; evidence?: { source_url: string; text: string } }[] } };
type Detail = Run & { settings: Record<string, unknown>; results: Result[]; queries: string[]; sources: string[];
  source_checks: { url: string; status: string; reason: string }[];
  errors_detail: { source_url?: string; phase?: string; error?: string }[]; legacy: boolean };
const input = "w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm focus:border-sky-500 focus:outline-none focus:ring-2 focus:ring-sky-100";
const button = "inline-flex min-h-10 items-center justify-center gap-2 rounded-lg border border-slate-200 bg-white px-3 py-2 text-sm font-medium hover:bg-slate-50 disabled:opacity-50";
const primary = `${button} !border-slate-900 !bg-slate-900 !text-white hover:!bg-slate-800`;
const label = "grid gap-2 text-sm font-medium text-slate-700";
const date = (value: string) => new Date(value).toLocaleString();
const readable = (value: string) => value.replaceAll("_", " ");
const url = (value?: string) => { try { const u = new URL(value || ""); return ["https:", "http:"].includes(u.protocol) ? u.href : undefined; } catch { return undefined; } };
const tone = (status: string) => ["match", "completed", "met"].includes(status) ? "bg-emerald-50 text-emerald-800" : ["error", "failed", "not_met"].includes(status) ? "bg-rose-50 text-rose-800" : ["uncertain", "partial", "unknown", "interrupted"].includes(status) ? "bg-amber-50 text-amber-800" : "bg-slate-100 text-slate-600";
const Badge = ({ value }: { value: string }) => <span className={`rounded-full px-2 py-1 text-xs font-medium ${tone(value)}`}>{readable(value)}</span>;

export default function JobSearches({ overview, onOpen }: { overview: Overview; onOpen: (job: Candidate) => void }) {
  const client = useQueryClient();
  const [edit, setEdit] = useState<Saved | null>(null);
  const [searchId, setSearchId] = useState("");
  const [page, setPage] = useState(1);
  const [runId, setRunId] = useState("");
  const [filter, setFilter] = useState("all");
  const [busy, setBusy] = useState("");
  const [error, setError] = useState("");
  const [description, setDescription] = useState("");
  const searches = useQuery({ queryKey: ["job-agent", "searches"], queryFn: () => request<{ items: Saved[] }>("/searches") });
  const runs = useQuery({ queryKey: ["job-agent", "search-runs", searchId, page], queryFn: () => request<{ items: Run[]; total_pages: number; total: number }>(`/search-runs?${new URLSearchParams({ ...(searchId ? { search_id: searchId } : {}), page: String(page) })}`), refetchInterval: 5000 });
  const detail = useQuery({ queryKey: ["job-agent", "search-run", runId], queryFn: () => request<Detail>(`/search-runs/${runId}`), enabled: !!runId, refetchInterval: 5000 });
  const refresh = () => client.invalidateQueries({ queryKey: ["job-agent"] });
  async function act(key: string, fn: () => Promise<void>) { setBusy(key); setError(""); try { await fn(); } catch (e) { setError(e instanceof Error ? e.message : "Something went wrong. Try again."); } finally { setBusy(""); } }
  function fresh(): Saved {
    const c = overview.config;
    return { id: "", revision: 0, config: { name: "", target_roles: c.target_roles, preferred_industries: c.preferred_industries,
      location_preferences: c.location_preferences, industry_mode: "required", location_mode: "preferred",
      employment_type: "any", employment_mode: "preferred", exclusions: "", additional_preferences: "",
      prefer_overseas_employers: c.prefer_overseas_employers, posted_within_days: 7, source_ids: c.search_source_ids,
      employer_urls: [], max_candidates: 10, max_sources: 6, schedule_enabled: false, timezone: "Asia/Kolkata", local_time: "01:00" } };
  }
  function update<K extends keyof Config>(key: K, value: Config[K]) { setEdit(old => old ? { ...old, config: { ...old.config, [key]: value } } : old); }
  const mode = (key: "industry_mode" | "location_mode" | "employment_mode") => <select aria-label={key.replaceAll("_", " ")} className={`${input} max-w-40`} value={edit?.config[key]} onChange={e => update(key, e.target.value as Mode)}><option value="required">Required</option><option value="preferred">Preferred</option></select>;
  const current = detail.data;
  return <section role="tabpanel" id="panel-searches" aria-labelledby="tab-searches" className="space-y-5">
    <div className="rounded-2xl bg-slate-900 p-6 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-medium uppercase tracking-widest text-sky-300">Discovery workspace</p><h2 className="mt-2 text-xl font-semibold">Focused searches. Traceable results.</h2><p className="mt-2 max-w-2xl text-sm text-slate-300">Save separate searches for different career paths. Every run keeps its settings, findings and explanations. Searching never submits an application.</p></div><button className={button + " text-slate-900"} onClick={() => { setEdit(fresh()); setRunId(""); }}><Plus size={16} />New search</button></div></div>
    {(error || searches.error || runs.error || detail.error) && <div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-sm text-rose-800">{error || String(searches.error || runs.error || detail.error)}<button className="ml-3 underline" onClick={() => { setError(""); refresh(); }}>Refresh</button></div>}
    {edit && <form className="space-y-5 rounded-2xl border border-sky-200 bg-sky-50/50 p-5" onSubmit={e => { e.preventDefault(); act("save", async () => { await request(`/searches${edit.id ? '/' + edit.id : ''}`, { revision: edit.revision, config: { ...edit.config, employer_urls: edit.config.employer_urls.map(u => u.trim()).filter(Boolean) } }); setEdit(null); refresh(); }); }}>
      <div className="flex items-center justify-between"><h3 className="font-semibold">{edit.id ? "Edit search" : "Create search"}</h3><button type="button" className={button} onClick={() => setEdit(null)}>Cancel</button></div>
      <div className="rounded-xl border border-sky-100 bg-white p-4"><label className={label}>Describe the search<textarea className={input} value={description} onChange={e => setDescription(e.target.value)} placeholder="Find AI agent engineering contracts in legal tech, remote from Colombia, posted this week. Exclude roles requiring a law degree." /></label><button type="button" className={`${button} mt-3`} disabled={!!busy || description.trim().length < 5} onClick={() => act("draft", async () => { const result = await request<{ config: Config }>("/searches/draft", { description }); setEdit(old => old ? { ...old, config: result.config } : old); })}>{busy === "draft" ? <Loader2 className="animate-spin" size={16} /> : <Sparkles size={16} />}Turn into editable settings</button><p className="mt-2 text-xs text-slate-500">Nothing runs until you save and choose Run now, or enable a schedule.</p></div>
      <label className={label}>Search name<input required maxLength={120} className={input} value={edit.config.name} onChange={e => update("name", e.target.value)} placeholder="Legal AI — LATAM remote" /></label>
      <div className="grid gap-4 md:grid-cols-2">
        <label className={label}>Roles and responsibilities · Required<textarea required className={input} value={edit.config.target_roles} onChange={e => update("target_roles", e.target.value)} /></label>
        <div className={label}><label htmlFor="search-industries">Industries</label>{mode("industry_mode")}<textarea id="search-industries" required className={input} value={edit.config.preferred_industries} onChange={e => update("preferred_industries", e.target.value)} /></div>
        <div className={label}><label htmlFor="search-location">Location and remote eligibility</label>{mode("location_mode")}<textarea id="search-location" required className={input} value={edit.config.location_preferences} onChange={e => update("location_preferences", e.target.value)} /></div>
        <div className={label}><label htmlFor="search-employment">Employment type</label>{mode("employment_mode")}<select id="search-employment" className={input} value={edit.config.employment_type} onChange={e => update("employment_type", e.target.value as Config["employment_type"])}><option value="any">Any employment type</option><option value="contract">Contract</option><option value="non_contract">Non-contract</option></select><label className={label}>Posted within (days)<input type="number" min={1} max={365} required className={input} value={edit.config.posted_within_days} onChange={e => update("posted_within_days", Number(e.target.value))} /></label></div>
        <label className={label}>Exclude jobs that…<textarea className={input} placeholder="Require a legal degree; require five years of courtroom experience" value={edit.config.exclusions} onChange={e => update("exclusions", e.target.value)} /></label>
        <label className={label}>Other preferences<textarea className={input} value={edit.config.additional_preferences} onChange={e => update("additional_preferences", e.target.value)} placeholder="Prefer small teams and hands-on ownership" /></label>
      </div>
      <p className="text-xs text-slate-500">Required mismatches are excluded. Missing evidence is shown as uncertain. Preferred mismatches remain visible.</p>
      <label className="flex gap-2 text-sm"><input type="checkbox" checked={edit.config.prefer_overseas_employers} onChange={e => update("prefer_overseas_employers", e.target.checked)} />Prefer employers based outside India</label>
      <details className="rounded-xl border border-slate-200 bg-white p-4"><summary className="cursor-pointer text-sm font-semibold">Sources and search breadth · {edit.config.source_ids.length} boards selected</summary><div className="mt-4 grid gap-2 sm:grid-cols-3">{overview.search_sources.items.map(source => <label key={source.id} className={`flex gap-2 text-sm ${!source.available ? 'text-slate-400' : ''}`}><input type="checkbox" disabled={!source.available} checked={edit.config.source_ids.includes(source.id)} onChange={e => update("source_ids", e.target.checked ? [...edit.config.source_ids, source.id] : edit.config.source_ids.filter(id => id !== source.id))} />{source.name}</label>)}</div><label className={`${label} mt-4`}>Employer careers pages (one URL per line)<textarea className={input} value={edit.config.employer_urls.join('\n')} onChange={e => update("employer_urls", e.target.value.split('\n'))} /></label><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className={label}>Candidate budget per run<input className={input} type="number" min={1} max={100} value={edit.config.max_candidates} onChange={e => update("max_candidates", Number(e.target.value))} /></label><label className={label}>Sources per run<input className={input} type="number" min={1} max={30} value={edit.config.max_sources} onChange={e => update("max_sources", Number(e.target.value))} /></label></div><p className="mt-2 text-xs text-slate-500">Sources rotate across runs. These are visible processing budgets, not a promise to exhaust the internet. Runs have a 30-minute time budget and retain partial results.</p></details>
      <div className="rounded-xl border border-indigo-100 bg-indigo-50 p-4"><label className="flex items-center gap-2 text-sm font-medium"><input type="checkbox" checked={edit.config.schedule_enabled} onChange={e => update("schedule_enabled", e.target.checked)} /><Clock size={16} />Run daily</label>{edit.config.schedule_enabled && <div className="mt-3 grid gap-3 sm:grid-cols-2"><label className={label}>Time<input type="time" required className={input} value={edit.config.local_time} onChange={e => update("local_time", e.target.value)} /></label><label className={label}>Timezone<input required className={input} value={edit.config.timezone} onChange={e => update("timezone", e.target.value)} placeholder="Asia/Kolkata" /></label></div>}<p className="mt-2 text-xs text-slate-500">The scheduler checks every five minutes. Queued searches run one at a time.</p></div>
      <button className={primary} disabled={!!busy}>{busy === "save" ? "Saving…" : "Save search"}</button>
    </form>}
    {!edit && <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{searches.isPending && <p className="text-sm text-slate-500">Loading saved searches…</p>}{searches.data?.items.map(search => <article key={search.id} className="flex flex-col rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-2"><h3 className="font-semibold">{search.config.name}</h3><button aria-label={`Edit ${search.config.name}`} className="rounded p-1 text-slate-500 hover:bg-slate-100" onClick={() => setEdit(search)}><Settings2 size={18} /></button></div><p className="mt-3 line-clamp-3 text-sm text-slate-600">{search.config.target_roles}</p><p className="mt-2 text-xs text-slate-500">{search.config.preferred_industries}</p><p className="mt-2 text-xs text-slate-500">{search.config.location_preferences}</p><div className="my-4 flex flex-wrap gap-2"><Badge value={search.config.employment_type === 'any' ? 'any employment' : search.config.employment_type} /><Badge value={`last ${search.config.posted_within_days} days`} /></div><p className="mb-4 text-xs text-indigo-700">{search.config.schedule_enabled ? `Daily · ${search.config.local_time} ${search.config.timezone}` : 'Manual runs only'}</p><div className="mt-auto flex gap-2"><button className={primary} disabled={!!busy} onClick={() => act(search.id, async () => { const r = await request<{ id: string }>(`/searches/${search.id}/run`, {}); setRunId(r.id); setFilter('all'); refresh(); })}><Play size={14} />{busy === search.id ? 'Queuing…' : 'Run now'}</button><button className={button} onClick={() => { setSearchId(search.id); setPage(1); setRunId(''); }}>Run history</button></div></article>)}</div>}
    <div className="rounded-xl border border-slate-200 bg-white">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 p-4"><h3 className="font-semibold">Run history</h3><select aria-label="Filter search runs" className={`${input} max-w-xs`} value={searchId} onChange={e => { setSearchId(e.target.value); setPage(1); }}><option value="">All searches, including earlier runs</option>{searches.data?.items.map(s => <option key={s.id} value={s.id}>{s.config.name}</option>)}</select></div>
      {runs.isPending && <p className="p-5 text-sm">Loading runs…</p>}{runs.data?.items.length === 0 && <p className="p-6 text-sm text-slate-500">No runs yet. Save a search and choose Run now.</p>}
      <div className="divide-y divide-slate-100">{runs.data?.items.map(run => <button key={run.id} className={`flex w-full flex-col gap-2 p-4 text-left hover:bg-sky-50 sm:flex-row sm:items-center sm:justify-between ${runId === run.id ? 'bg-sky-50' : ''}`} onClick={() => { setRunId(run.id); setFilter('all'); }}><div><span className="text-sm font-medium">{run.name}</span><p className="mt-1 text-xs text-slate-500">{date(run.started_at)} · {run.trigger}</p></div><div className="flex flex-wrap items-center gap-3 text-xs text-slate-600"><span>{run.new_jobs} new · {run.duplicates} already known · {run.errors} errors</span><Badge value={run.status} /></div></button>)}</div>
      {!!runs.data?.total && <div className="flex items-center justify-between border-t p-3 text-xs"><span>{runs.data.total} runs · Page {page} of {runs.data.total_pages}</span><div className="flex gap-2"><button className={button} disabled={page <= 1} onClick={() => setPage(page-1)}>Previous</button><button className={button} disabled={page >= runs.data.total_pages} onClick={() => setPage(page+1)}>Next</button></div></div>}
    </div>
    {runId && <div className="rounded-2xl border border-sky-200 bg-white p-5"><button className="mb-3 flex items-center gap-1 text-xs text-slate-500" onClick={() => setRunId('')}><ChevronLeft size={14} />Close run details</button>{detail.isPending && <p>Loading results…</p>}{current && <>
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-semibold">{current.name}</h3><p className="mt-1 text-xs text-slate-500">{date(current.started_at)}{current.completed_at && ` → ${date(current.completed_at)}`}</p></div><Badge value={current.status} /></div>
      <p role="status" className="my-4 flex items-center gap-2 rounded-lg bg-sky-50 p-3 text-sm text-sky-900">{['running','queued'].includes(current.status) && <Loader2 size={16} className="animate-spin" />}{current.status === 'queued' ? 'Waiting for the search worker. Another search may be using the research lane.' : current.phase}</p>
      <p className="mb-4 text-sm text-slate-600">{current.results.length} findings · {current.new_jobs} new jobs · {current.duplicates} already in queue · {current.errors} errors</p>
      <details className="mb-4 rounded-lg border p-3"><summary className="cursor-pointer text-sm font-medium">Settings and sources used for this run</summary><p className="my-2 text-xs text-slate-500">This snapshot does not change when you edit the saved search.</p><pre className="max-h-80 overflow-auto whitespace-pre-wrap break-words rounded bg-slate-50 p-3 text-xs">{JSON.stringify(current.settings, null, 2)}</pre><h4 className="mt-3 text-sm font-medium">Queries</h4><ul className="list-inside list-disc text-xs text-slate-600">{current.queries.map((q,i) => <li key={i}>{q}</li>)}</ul><h4 className="mt-3 text-sm font-medium">Sources assigned</h4>{current.sources.map((s,i) => <p className="break-all text-xs" key={i}><a href={url(s)} target="_blank" rel="noreferrer" className="text-sky-700 underline">{s}</a></p>)}<h4 className="mt-3 text-sm font-medium">Source checks reported by the researcher</h4>{!current.source_checks.length && <p className="text-xs text-slate-500">No source-check report was saved. Assigned sources alone do not prove they were searched.</p>}{current.source_checks.map((s,i) => <p className="mt-1 break-words text-xs" key={i}>{s.url} · {s.status} · {s.reason}</p>)}</details>
      {current.legacy && <p className="mb-4 text-xs text-amber-800">Earlier run: showing recorded decisions. Detailed requirement checks and queue links were not recorded at the time.</p>}
      {!!current.errors_detail.length && <details className="mb-4 rounded-lg border border-rose-100 bg-rose-50 p-3"><summary className="cursor-pointer text-sm text-rose-800">{current.errors_detail.length} processing errors</summary>{current.errors_detail.map((e,i) => <p key={i} className="mt-2 break-words text-xs text-rose-800">{e.phase || e.source_url}: {e.error}</p>)}</details>}
      <div className="mb-4 flex flex-wrap gap-2">{['all','match','uncertain','excluded','error','pending'].map(f => <button key={f} className={`${button} ${filter===f ? '!border-sky-500 !bg-sky-50' : ''}`} onClick={() => setFilter(f)}>{readable(f)} ({current.results.filter(r => f==='all' || r.outcome===f).length})</button>)}</div>
      <div className="space-y-3">{current.results.filter(r => filter==='all' || r.outcome===filter).map((r,i) => <article key={`${r.candidate?.source_url}-${i}`} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><h4 className="font-medium">{r.candidate?.title || 'Unresolved job'}</h4><p className="mt-1 text-sm text-slate-600">{r.candidate?.firm_name} · {r.decision?.location || 'Location unknown'}</p></div><Badge value={r.outcome} /></div><p className="my-3 text-sm text-slate-700">{r.reason}</p><div className="flex flex-wrap gap-2 text-xs text-slate-500">{r.already_known && <Badge value="Already in your queue" />}<span>{r.decision?.posted_date || 'Posting date unknown'}</span>{r.contract_status && <span>· {readable(r.contract_status)}</span>}{r.contacts && <span>· {r.contacts.verified} verified contacts</span>}</div>{!!r.decision?.search_checks?.length && <details className="mt-3"><summary className="cursor-pointer text-xs font-medium text-sky-700">Why this result?</summary><div className="mt-2 space-y-2">{r.decision.search_checks.map((c,j) => <div className="rounded bg-slate-50 p-2 text-xs" key={j}><span className="font-medium capitalize">{c.criterion}</span> · <Badge value={c.result} /><p className="mt-2">{c.reason}</p>{c.evidence && <blockquote className="mt-2 border-l-2 border-sky-200 pl-2 text-slate-500">{c.evidence.text}</blockquote>}</div>)}</div></details>}<div className="mt-3 flex gap-2">{url(r.candidate?.source_url) && <a className={button} href={url(r.candidate?.source_url)} target="_blank" rel="noreferrer">View listing<ArrowUpRight size={14} /></a>}{r.candidate_id && <button className={button} disabled={!!busy} onClick={() => act('open', async () => onOpen(await request<Candidate>(`/jobs/${r.candidate_id}`)))}>Open saved job</button>}</div></article>)}</div>
      {!current.results.length && <p className="py-6 text-center text-sm text-slate-500">{['running','queued'].includes(current.status) ? 'Findings will appear as research progresses.' : 'No findings were recorded. Check source reports and errors, or broaden the search.'}</p>}
    </>}</div>}
  </section>;
}
