"""initial_schema

Revision ID: acf4fe2063fa
Revises: 
Create Date: 2026-01-28 08:51:19.723662

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'acf4fe2063fa'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dispatcher_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_dispatcher_events_decision', 'dispatcher_events', ['decision'], unique=False)
    op.create_index('ix_dispatcher_events_timestamp', 'dispatcher_events', ['timestamp'], unique=False)
    op.create_table('patients',
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('order_created', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('intake_status', sa.String(length=20), nullable=False),
    sa.Column('has_called_in_before', sa.Boolean(), nullable=False),
    sa.Column('has_abandoned_before', sa.Boolean(), nullable=False),
    sa.Column('ai_called_before', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_outcome', sa.String(length=32), nullable=True),
    sa.Column('due_by', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('priority_bucket', sa.Integer(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('patient_id')
    )
    op.create_index('ix_patients_phone', 'patients', ['phone'], unique=False)
    op.create_index('ix_patients_priority_due', 'patients', ['priority_bucket', 'due_by'], unique=False)
    op.create_table('queue_state_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('global_calls_waiting', sa.Integer(), nullable=False),
    sa.Column('global_oldest_wait_seconds', sa.Integer(), nullable=False),
    sa.Column('global_agents_available', sa.Integer(), nullable=False),
    sa.Column('global_agents_logged_in', sa.Integer(), nullable=False),
    sa.Column('outbound_allowed', sa.Boolean(), nullable=False),
    sa.Column('stable_polls_count', sa.Integer(), nullable=False),
    sa.Column('ami_connected', sa.Boolean(), nullable=False),
    sa.Column('queues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_queue_state_snapshots_timestamp', 'queue_state_snapshots', ['timestamp'], unique=False)
    op.create_table('simulation_scenarios',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('ami_connected', sa.Boolean(), nullable=False),
    sa.Column('queues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('patients', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dispatcher', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('system_enabled', sa.Boolean(), nullable=False),
    sa.Column('business_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('queue_thresholds', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.CheckConstraint('id = 1', name='singleton_settings'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_logs',
    sa.Column('call_id', sa.String(length=64), nullable=False),
    sa.Column('patient_id', sa.String(length=64), nullable=False),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('priority_bucket', sa.Integer(), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('transfer_attempted', sa.Boolean(), nullable=False),
    sa.Column('transfer_success', sa.Boolean(), nullable=False),
    sa.Column('voicemail_left', sa.Boolean(), nullable=False),
    sa.Column('sms_sent', sa.Boolean(), nullable=False),
    sa.Column('queue_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('transcript', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('call_id')
    )
    op.create_index('ix_call_logs_outcome', 'call_logs', ['outcome'], unique=False)
    op.create_index('ix_call_logs_patient_id', 'call_logs', ['patient_id'], unique=False)
    op.create_index('ix_call_logs_started_at', 'call_logs', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_call_logs_started_at', table_name='call_logs')
    op.drop_index('ix_call_logs_patient_id', table_name='call_logs')
    op.drop_index('ix_call_logs_outcome', table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_table('system_settings')
    op.drop_table('simulation_scenarios')
    op.drop_index('ix_queue_state_snapshots_timestamp', table_name='queue_state_snapshots')
    op.drop_table('queue_state_snapshots')
    op.drop_index('ix_patients_priority_due', table_name='patients')
    op.drop_index('ix_patients_phone', table_name='patients')
    op.drop_table('patients')
    op.drop_index('ix_dispatcher_events_timestamp', table_name='dispatcher_events')
    op.drop_index('ix_dispatcher_events_decision', table_name='dispatcher_events')
    op.drop_table('dispatcher_events')
    # ### end Alembic commands ###
