"""add_allow_live_calls_and_allowed_phones

Revision ID: c7d960b54d3b
Revises: acf4fe2063fa
Create Date: 2026-02-02 04:36:29.593304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c7d960b54d3b'
down_revision: Union[str, None] = 'acf4fe2063fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('allow_live_calls', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('system_settings', sa.Column('allowed_phones', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_settings', 'allowed_phones')
    op.drop_column('system_settings', 'allow_live_calls')
    # ### end Alembic commands ###
