"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Bell, Eye, Pause, Play, RefreshCw, Save, UserPlus, X } from "lucide-react";
import { apiUrl } from "@/lib/api";

type Subscription = { pif_id: string; firm_name: string; domain: string; recipient_name: string; recipient_email: string; title: string; status: string; reason: string | null; last_review_researched_at: string | null };
type Delivery = { id: string; pif_id: string; recipient_name: string; recipient_email: string; status: string; subject: string; body: string; created_at: string; error: string | null };
type Config = { enabled: boolean; auto_send: boolean; daily_limit: number; postal_address: string; sender: string; enrollment_requested?: boolean; last_enrollment?: { titles_remaining: number }; last_run?: { status: string; finished_at?: string; error?: string; enrollment_error?: string; prepared?: number; sent?: number } };
type State = { config: Config; blockers: string[]; counts: Record<string, number>; review_collection: { mode: string; window_days: number }; subscriptions: Subscription[]; deliveries: Delivery[] };

async function request(path = "", body?: unknown): Promise<any> {
  const response = await fetch(apiUrl(`/api/review-alerts${path}`), { credentials: "include", method: body === undefined ? "GET" : "POST", headers: { "Content-Type": "application/json" }, body: body === undefined ? undefined : JSON.stringify(body) });
  if (response.status === 401) { window.location.href = "/login?next=/review-alerts"; throw new Error("Sign in required"); }
  const result = await response.json();
  if (!response.ok) throw new Error(typeof result.detail === "string" ? result.detail : JSON.stringify(result.detail));
  return result;
}

export default function ReviewAlertsPage() {
  const [data, setData] = useState<State | null>(null);
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const [search, setSearch] = useState("");
  const [tab, setTab] = useState("firms");
  const [preview, setPreview] = useState<Delivery | null>(null);
  const [address, setAddress] = useState("");
  const [sender, setSender] = useState("");
  const [dailyLimit, setDailyLimit] = useState(25);
  const [loaded, setLoaded] = useState(false);
  const load = useCallback(async () => { try { const result = await request(); setData(result); setError(""); return result as State; } catch (e) { setError(String(e)); } }, []);
  useEffect(() => { void load(); const timer = setInterval(load, 30000); return () => clearInterval(timer); }, [load]);
  useEffect(() => { if (data && !loaded) { setAddress(data.config.postal_address); setSender(data.config.sender); setDailyLimit(data.config.daily_limit); setLoaded(true); } }, [data, loaded]);
  useEffect(() => { const close = (e: KeyboardEvent) => { if (e.key === "Escape") setPreview(null); }; window.addEventListener("keydown", close); return () => window.removeEventListener("keydown", close); }, []);
  async function act(path: string, body: unknown = {}) { setBusy(true); setError(""); try { await request(path, body); await load(); } catch (e) { setError(String(e)); } finally { setBusy(false); } }
  const button = "inline-flex items-center justify-center gap-2 rounded-md border border-neutral-300 bg-white px-3 py-2 text-sm font-medium disabled:opacity-50 hover:bg-neutral-50";
  const iconButton = "inline-flex h-9 w-9 items-center justify-center rounded-md border border-neutral-200 hover:bg-neutral-100 disabled:opacity-50";
  const filtered = data?.subscriptions.filter(s => `${s.firm_name} ${s.recipient_name} ${s.recipient_email} ${s.status}`.toLowerCase().includes(search.toLowerCase())) || [];
  return <main className="mx-auto max-w-7xl space-y-6 p-4 md:p-8">
    <header className="flex flex-wrap items-center justify-between gap-4 border-b border-neutral-200 pb-5"><h1 className="flex items-center gap-3 text-2xl font-semibold"><Bell className="h-6 w-6 text-teal-700" />Review Alerts</h1><div className="flex flex-wrap gap-2"><Link className={button} href="/comms">Communications</Link><button className={iconButton} title="Refresh" aria-label="Refresh" onClick={() => void load()}><RefreshCw size={16} /></button><button disabled={busy} className={button} onClick={() => void act("/run")}><Play size={16} />Process collected reviews</button></div></header>
    {error && <div role="alert" className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</div>}
    {!data ? <p className="text-sm text-neutral-500">Loading...</p> : <>
      <section className="grid grid-cols-2 gap-4 border-b border-neutral-200 pb-5 md:grid-cols-4">{[["Monitored firms", data.subscriptions.filter(s => s.status === "active").length], ["Queued", data.counts.queued || 0], ["Sent", data.counts.sent || 0], ["Needs review", (data.counts.uncertain || 0) + data.subscriptions.filter(s => s.status === "paused").length]].map(([label, value]) => <div key={label} className="border-l-2 border-teal-500 pl-4"><p className="text-sm text-neutral-600">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></div>)}</section>
      <section className="flex flex-wrap items-center gap-6 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={data.config.enabled} disabled={busy} onChange={e => void act("/config", { enabled: e.target.checked })} />Monitoring</label><label className="flex items-center gap-2"><input type="checkbox" checked={data.config.auto_send} disabled={busy} onChange={e => void act("/config", { auto_send: e.target.checked })} />Automatic emails</label><span className="text-neutral-500">Last cycle: {data.config.last_run?.status || "Not run"}{data.config.last_run?.finished_at ? ` · ${new Date(data.config.last_run.finished_at).toLocaleString()}` : ""}</span></section>
      <p className="rounded-md border border-sky-200 bg-sky-50 px-4 py-3 text-sm text-sky-900">Reviews are collected only when nightly firm maintenance checks a firm. A review with a verified publication date in the latest {data.review_collection.window_days} days can generate an alert.</p>
      {data.blockers.length > 0 && <div className="border-l-4 border-amber-500 bg-amber-50 px-4 py-3 text-sm text-amber-900"><strong>Sending held</strong><ul className="mt-1 list-inside list-disc">{data.blockers.map(b => <li key={b}>{b}</li>)}</ul></div>}
      {data.config.last_run?.error && <p className="text-sm text-red-700">{data.config.last_run.error}</p>}
      {data.config.enrollment_requested && <p role="status" className="border-l-4 border-sky-500 bg-sky-50 px-4 py-3 text-sm text-sky-900">Leader verification {data.config.last_run?.status === "running" ? "in progress" : "queued"}{data.config.last_enrollment ? ` · ${data.config.last_enrollment.titles_remaining} titles remaining` : ""}</p>}
      {data.config.last_run?.enrollment_error && <p className="text-sm text-red-700">Leader verification: {data.config.last_run.enrollment_error}</p>}
      <details className="border-y border-neutral-200 py-3"><summary className="cursor-pointer text-sm font-semibold">Sending settings</summary><form className="mt-4 grid gap-4 sm:grid-cols-2" onSubmit={e => { e.preventDefault(); void act("/config", { postal_address: address, sender, daily_limit: dailyLimit }); }}><label className="text-sm">Business mailing address<textarea required className="mt-1 block w-full rounded-md border p-2" value={address} onChange={e => setAddress(e.target.value)} /></label><label className="text-sm">Sender email<input type="email" className="mt-1 block w-full rounded-md border p-2" value={sender} onChange={e => setSender(e.target.value)} placeholder="Monitored mailbox" /></label><label className="text-sm">Maximum emails per day<input type="number" min={1} max={100} className="ml-3 w-20 rounded-md border p-2" value={dailyLimit} onChange={e => setDailyLimit(Number(e.target.value))} /></label><button className={`${button} justify-self-start`} disabled={busy}><Save size={16} />Save settings</button></form></details>
      <div className="flex flex-wrap items-center justify-between gap-3"><div className="flex gap-4 border-b border-neutral-200">{["firms", "deliveries"].map(t => <button key={t} onClick={() => setTab(t)} className={`border-b-2 px-1 py-2 text-sm font-medium capitalize ${tab === t ? "border-teal-600 text-teal-800" : "border-transparent text-neutral-500"}`}>{t}</button>)}</div><button disabled={busy} className={button} onClick={() => { if (confirm("Enroll eligible PI firms with one selected leader each? Existing unsubscribed firms will stay excluded.")) void act("/enroll?dry_run=false"); }}><UserPlus size={16} />Enroll eligible firms</button></div>
      {tab === "firms" ? <section><input aria-label="Search firms and recipients" placeholder="Search firms, people, email, status..." className="mb-4 w-full rounded-md border border-neutral-300 px-3 py-2 text-sm sm:max-w-md" value={search} onChange={e => setSearch(e.target.value)} /><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-y bg-neutral-50 text-neutral-500"><tr>{["Firm", "Selected leader", "Status", "Last review check", ""].map(t => <th key={t} className="p-3 font-medium">{t}</th>)}</tr></thead><tbody>{filtered.map(s => <tr key={s.pif_id} className="border-b border-neutral-100"><td className="p-3"><Link href={`/leads?firm=${s.pif_id}`} className="font-medium text-teal-800">{s.firm_name}</Link><p className="text-xs text-neutral-500">{s.domain}</p></td><td className="p-3"><p>{s.recipient_name}</p><p className="text-xs text-neutral-500">{s.title}</p><p className="text-xs">{s.recipient_email}</p></td><td className="max-w-[240px] p-3"><span className={s.status === "active" ? "text-teal-700" : "text-amber-800"}>{s.status}</span>{s.reason && <p className="mt-1 text-xs text-neutral-500">{s.reason}</p>}</td><td className="p-3 text-xs">{s.last_review_researched_at ? new Date(s.last_review_researched_at).toLocaleString() : "Not yet"}</td><td className="p-3"><div className="flex gap-2">{s.status !== "unsubscribed" && <><button className={iconButton} disabled={busy} title={s.status === "active" ? "Pause" : "Resume"} aria-label={s.status === "active" ? "Pause" : "Resume"} onClick={() => void act(`/subscriptions/${s.pif_id}`, { status: s.status === "active" ? "paused" : "active" })}>{s.status === "active" ? <Pause size={15} /> : <Play size={15} />}</button><button className={iconButton} disabled={busy} title="Unsubscribe firm" aria-label="Unsubscribe firm" onClick={() => { if (confirm(`Unsubscribe ${s.firm_name}?`)) void act(`/subscriptions/${s.pif_id}`, { status: "unsubscribed" }); }}><X size={15} /></button></>}</div></td></tr>)}</tbody></table>{!filtered.length && <p className="py-8 text-center text-sm text-neutral-500">No matching firms</p>}</div></section> : <section className="divide-y">{data.deliveries.map(d => <article key={d.id} className="flex items-start justify-between gap-4 py-4"><div className="min-w-0"><h2 className="text-sm font-medium">{d.subject}</h2><p className="break-words text-xs text-neutral-500">{d.recipient_name} · {d.recipient_email}</p><p className="mt-1 text-xs">{d.status} · {new Date(d.created_at).toLocaleString()}</p>{d.error && <p className="mt-1 text-xs text-red-700">{d.error}</p>}</div><button className={iconButton} title="View full email" aria-label="View full email" onClick={() => setPreview(d)}><Eye size={16} /></button></article>)}{!data.deliveries.length && <p className="py-8 text-center text-sm text-neutral-500">No review-alert emails yet</p>}</section>}
    </>}
    {preview && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onClick={() => setPreview(null)}><section role="dialog" aria-modal="true" aria-label="Review alert email" className="max-h-[85vh] w-full max-w-2xl overflow-y-auto rounded-lg bg-white p-6 shadow-xl" onClick={e => e.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><h2 className="text-base font-semibold">{preview.subject}</h2><p className="mt-1 break-all text-sm text-neutral-500">To: {preview.recipient_name} &lt;{preview.recipient_email}&gt;</p><p className="text-xs text-neutral-500">{preview.status}</p></div><button autoFocus className={iconButton} aria-label="Close preview" onClick={() => setPreview(null)}><X size={16} /></button></div><pre className="mt-5 whitespace-pre-wrap break-words border-t pt-5 font-sans text-sm leading-6">{preview.body}</pre></section></div>}
  </main>;
}
